/**
 * Static demo-run data bundled with the app — a judge clicking the public URL
 * with no backend sees the full run. All values originate from
 * public/runs/demo-canonical/manifest.json (generated by relay-cli
 * gen-demo-run, conformance-asserted against packages/test-vectors).
 */
import type { RunManifest } from "@proofline/event-model";
import manifestJson from "../public/runs/demo-canonical/manifest.json";
import deploymentJson from "../../../packages/config/deployments/base-sepolia.json";
import vectorJson from "../../../packages/test-vectors/match-outcome-v1.json";
import fixtureJson from "../../../packages/test-vectors/fixture-982341.json";

export const demoManifest = manifestJson as unknown as RunManifest;

export const deployment = deploymentJson as {
  chainId: number;
  explorerBaseUrl: string;
  deployedAtBlock: number;
  contracts: Record<string, string>;
  guardianSet: string[];
  quorum: number;
  registeredEmitter: string;
  forwarder: string;
  deployTxHashes: Record<string, string>;
};

export const vector = vectorJson as {
  domainSeparator: string;
  outcome: Record<string, string | number> & {
    txlineProgramId: string;
    dailyRootAccount: string;
    validationInstructionHash: string;
    proofBundleHash: string;
  };
  sourceEmitter: string;
  encodedPayload: string;
  attestationId: string;
};

export interface FixtureRecord {
  action: string;
  statusId: number;
  period: number;
  sequence: string;
  participant1Score: number;
  participant2Score: number;
  timestampMs: number;
}

export const demoFixtureFile = fixtureJson as unknown as {
  description: string;
  fixtureId: string;
  participant1: string;
  participant2: string;
  competition: string;
  records: FixtureRecord[];
  rootAccount: string;
  strategy: string;
  wormhole: { emitterBase58: string; sequence: string };
  destinationChain: number;
};

export const explorer = deployment.explorerBaseUrl;
export const explorerAddress = (a: string) => `${explorer}/address/${a}`;
export const explorerTx = (h: string) => `${explorer}/tx/${h}`;

export const shortHex = (h: string, head = 10, tail = 6) =>
  h.length > head + tail + 1 ? `${h.slice(0, head)}…${h.slice(-tail)}` : h;
